Modify for OneWattSpot detection

diff --git a/systemd/ax25/ax25-upd b/systemd/ax25/ax25-upd
--- a/systemd/ax25/ax25-upd
+++ b/systemd/ax25/ax25-upd
@@ -16,10 +16,20 @@ SERIALPORT_DIREWOLF="/tmp/kisstnc"
 
 firmware_prodfile="/sys/firmware/devicetree/base/hat/product"
 firmware_prod_idfile="/sys/firmware/devicetree/base/hat/product_id"
+firmware_vendorfile="/sys/firmware/devicetree/base/hat/vendor"
+
+PROD_ID_NAMES=("INVALID" "INVALID" "UDRC" "UDRC II" "1WSpot")
+NWDIG_VENDOR_NAME="NW Digital Radio"
 
 function dbgecho { if [ ! -z "$DEBUG" ] ; then echo "$*"; fi }
 
-# ===== udrc id_check =====
+# ===== function EEPROM id_check
+# Return code:
+# 0 = no EEPROM or no device tree found
+# 1 = HAT found but not a UDRC
+# 2 = UDRC
+# 3 = UDRC II
+# 4 = 1WSpot
 
 function id_check() {
 # Initialize to EEPROM not found
@@ -28,36 +38,46 @@ udrc_prod_id=0
 if [ -f $firmware_prodfile ] ; then
    # Read product file
    UDRC_PROD="$(cat $firmware_prodfile)"
-   sizeprodstr=${#UDRC_PROD}
-   dbgecho "UDRC_PROD: $UDRC_PROD, size: $sizeprodstr"
-   if (( $sizeprodstr < 34 )) ; then
-      dbgecho "Probably not a Universal Digital Radio Controller: $UDRC_PROD"
-      udrc_prod_id=1
-   elif [ "${UDRC_PROD:0:34}" == "Universal Digital Radio Controller" ] ; then
-      dbgecho "Definitely some kind of UDRC"
-   else
-      echo "Found something but not a UDRC: $UDRC_PROD"
-      udrc_prod_id=1
-   fi
-
-   # get last 2 characters in product file
-   UDRC_PROD=${UDRC_PROD: -2}
+   # Read vendor file
+   FIRM_VENDOR="$(cat $firmware_vendorfile)"
    # Read product id file
    UDRC_ID="$(cat $firmware_prod_idfile)"
    #get last character in product id file
    UDRC_ID=${UDRC_ID: -1}
-   udrc_prod_id=$UDRC_ID
 
-   dbgecho "Product: $UDRC_PROD, Id: $UDRC_ID"
-   if [ "$UDRC_PROD" == "II" ] && [ "$UDRC_ID" == "3" ] ; then
-      dbgecho "Found a UDRC II"
-      UDRCII=true
-   elif [ "$UDRC_PROD" == "er" ] && [ "$UDRC_ID" == "2" ] ; then
-      dbgecho "Found an original UDRC"
+   dbgecho "UDRC_PROD: $UDRC_PROD, ID: $UDRC_ID"
+
+   if [[ "$FIRM_VENDOR" == "$NWDIG_VENDOR_NAME" ]] ; then
+      case $UDRC_PROD in
+         "Universal Digital Radio Controller")
+            udrc_prod_id=2
+         ;;
+         "Universal Digital Radio Controller II")
+            udrc_prod_id=3
+         ;;
+         "1WSpot")
+            udrc_prod_id=4
+         ;;
+         *)
+            echo "Found something but not a UDRC: $UDRC_PROD"
+            udrc_prod_id=1
+         ;;
+      esac
    else
+
+      dbgecho "Probably not a NW Digital Radio product: $FIRM_VENDOR"
       udrc_prod_id=1
    fi
 
+   if [ udrc_prod_id != 0 ] && [ udrc_prod_id != 1 ] ; then
+      if (( UDRC_ID == udrc_prod_id )) ; then
+         dbgecho "Product ID match: $udrc_prod_id"
+      else
+         echo "Product ID MISMATCH $UDRC_ID : $udrc_prod_id"
+         udrc_prod_id=1
+      fi
+   fi
+   dbgecho "Found HAT for ${PROD_ID_NAMES[$UDRC_ID]} with product ID: $UDRC_ID"
 else
    # RPi HAT ID EEPROM may not have been programmed in engineering samples
    # or there is no RPi HAT installed.
@@ -80,25 +100,47 @@ fi
 
 # Check which UDRC product is found
 id_check
+id_check_ret="$?"
 
-if [ "$UDRCII" = true ]; then
-# use port 2 with mkiss
-   pseudoterm=$($SBINDIR/mkiss $SERIALPORT_DIREWOLF none /dev/ptmx | tail -1)
-   echo "using mkiss with UDRC II and pseudo term=$pseudoterm on port 2"
-   $SBINDIR/kissattach  ${pseudoterm} ${PORTNAME} 44.24.197.66 >/tmp/ax25-config.tmp
-   dbgecho "kissattach return: $?"
+# Initialize kissattach return code
+kissattach_ret=-1
 
-else
+case $id_check_ret in
+0|1)
+   echo "No UDRC found, exiting"
+   exit 1
+;;
+2)
+   echo "Original UDRC is installed."
 # use port 1 with mkiss
    pseudoterm=$($SBINDIR/mkiss $SERIALPORT_DIREWOLF /dev/ptmx none | tail -1)
    echo "using mkiss with UDRC and pseudo term=$pseudoterm on port 1"
    $SBINDIR/kissattach  ${pseudoterm} ${PORTNAME} 44.24.197.66 >/tmp/ax25-config.tmp
+   kissattach_ret=$?
+;;
+3)
+   echo "UDRC II installed"
+# use port 2 with mkiss
+   pseudoterm=$($SBINDIR/mkiss $SERIALPORT_DIREWOLF none /dev/ptmx | tail -1)
+   echo "using mkiss with UDRC II and pseudo term=$pseudoterm on port 2"
+   $SBINDIR/kissattach  ${pseudoterm} ${PORTNAME} 44.24.197.66 >/tmp/ax25-config.tmp
+   kissattach_ret=$?
+;;
+4)
+   echo "One Watt Spot installed"
+# use port 1 with mkiss
+   pseudoterm=$($SBINDIR/mkiss $SERIALPORT_DIREWOLF /dev/ptmx none | tail -1)
+   echo "using mkiss with UDRC and pseudo term=$pseudoterm on port 1"
+   $SBINDIR/kissattach  ${pseudoterm} ${PORTNAME} 44.24.197.66 >/tmp/ax25-config.tmp
+   kissattach_ret=$?
+;;
+*)
+   echo "Invalid udrc id ... exiting"
+   exit 1
+;;
+esac
 
-#   echo "using kissattach without mkiss"
-# Attach KISS-device to Port - audio index port 0
-#   $SBINDIR/kissattach  ${SERIALPORT_DIREWOLF} ${PORTNAME} 44.24.197.66 >/tmp/ax25-config.tmp
-   dbgecho "kissattach return: $?"
-fi
+dbgecho "kissattach return: $?"
 
 /etc/ax25/ax25dev-parms
 
